# FROM referes to base OS of the image
# The dockerfile's first instruction should be FROM
# Command to build image docker build -t <image-name>:<version> . 
# . means dockerfile is in current directory
FROM almalinux:9